In [1]:
import pandas as pd
import numpy as np
import nltk
import io
    
df = pd.read_csv(r'D:\Travelytics Project\Data\Airline Tweets.csv',encoding='utf-8-sig')


#New unlabeled Dataset
df_new_data = pd.read_csv(u'D:\Travelytics Project\Data\Preprocessed Tweet Data.csv')
#df_fresh_data= df_new_data[["Text"]]


In [2]:
'''Textblob sentiment analysis
Code was used from:
https://towardsdatascience.com/having-fun-with-textblob-7e9eed783d3f
https://stackoverflow.com/questions/43485469/apply-textblob-in-for-each-row-of-a-dataframe
'''

from textblob import TextBlob

#replace null values with empty space
noNull = df['Text'].fillna("")

df['sentiment'] = noNull.apply(lambda tweet: TextBlob(tweet).sentiment)

df

Unnamed: 0  number keyword  \
0      0.943430   65789      TT   
1      0.970177   49400      NK   
2      0.143541   60959     TOM   
3      0.360187   77607      VA   
4      0.779308   58487     TOM   
5      0.359184   77943      VA   
6      0.153355   86771      WN   
7      0.788929   46885      LS   
8      0.909354   22436      BE   
9      0.094547   72338      UA   
10     0.160353   16399      B6   
11     0.227760   52091      QF   
12     0.629340   65344      TT   
13     0.189803   60377     TOM   
14     0.918695    1581      AA   
15     0.502972   54854      TO   
16     0.216359   22399      BE   
17     0.409520   15645      AS   
18     0.910300   45944      LS   
19     0.096877    5540      AA   
20     0.536603   45306      LS   
21     0.131978   62805     TOM   
22     0.171452   12373      AF   
23     0.951226   52094      QF   
24     0.668162     811      AA   
25     0.806601   11809      AF   
26     0.661338   83304      W6   
27     0.967721   68383      U2   
28     0.667780    7503      AC   
29     0.169100   55744      TO   
..          ...     ...     ...   
293    0.713540   14489      AS   
294    0.771143   48281      LS   
295    0.367883   60048     TOM   
296    0.181775   77281      VA   
297    0.991126   65130      TT   
298    0.243927   84326      W6   
299    0.280581   33984      FR   
300    0.332174    7005      AC   
301    0.648780   84521      W6   
302    0.626496   84160      W6   
303    0.662308   87809      WN   
304    0.570786   88396      WN   
305    0.088233   45519      LS   
306    0.412121    5212      AA   
307    0.932134   16202      B6   
308    0.363049   61827     TOM   
309    0.272725    7605      AC   
310    0.587596   18822      B6   
311    0.520768   50257      NK   
312    0.826819   11803      AF   
313    0.971511   15251      AS   
314    0.079147   63374     TOM   
315    0.117393    5936      AA   
316    0.769756   50964      NK   
317    0.519524   80292      VY   
318    0.510298   15909      AS   
319    0.703480   63020     TOM   
320    0.085105   58046     TOM   
321    0.260572   42866      LH   
322    0.299976   76133      UX   

                                                  Text  \
0     Hi there  the best team to assist you is our ...   
1     We re awfully sorry to hear about that  Pleas...   
2    RT   In #Namibia  Melissa and Anna Marie found...   
3     We re sorry to hear this Peter  We would reco...   
4    RT   The Q  #TUIResults are out and show signi...   
5     Hi Olan  we are so pleased to hear this feedb...   
6     Hi there  On May          we will open our sc...   
7     Sorry to hear that  We do hope to see you aga...   
8     Hi Charlotte  thanks for getting in touch  I ...   
9     We re sorry for the disruption  Shea  Can you...   
10    That s disappointing  We can issue a     cred...   
11    Perfection on a plate  We enjoyed having you ...   
12    Our thoughts are with you Walter  keep fighti...   
13   We ve launched our brand new Investor Relation...   
14    We love having you fly with us and will gladl...   
15    Hello  I am sorry for the inconveniences  Can...   
16    Thanks for confirming this with me Emma  I ve...   
17    We re sorry to hear about any frustration  If...   
18    Thanks for getting back to us  we would recom...   
19    We want all of our customers to feel welcome ...   
20    Hi Laura  If you don t cancel the individual ...   
21   Family Holiday Association launches     for   ...   
22        If your query is regarding your trip  ple...   
23    This isn t what we like to hear Jimmy  Can yo...   
24    We re so sorry for the extra travel time toda...   
25    Hello   not a problem  Send us a DM confirmin...   
26    Hey Jose  since those services are different ...   
27    Hi Justin  thanks for getting in touch  I m n...   
28    Please DM us your booking details so we may a...   
29    Hi April  it should be possible to check in  ...   
..                                  

In [3]:
'''Vader from nltk for sentiment analysis
Code was used from:
http://www.nltk.org/howto/sentiment.html
https://stackoverflow.com/questions/57803412/applying-sentimentintensityanalyzer-function-on-each-row-of-the-dataframe-prov
http://t-redactyl.io/blog/2017/04/using-vader-to-handle-sentiment-analysis-with-social-media-text.html
https://stackoverflow.com/questions/52323299/python-return-elif-statement
'''


nltk.download('vader_lexicon') #download if don't have vader
from nltk.sentiment.vader import SentimentIntensityAnalyzer


def get_sentiment(row, **kwargs):
    sid = SentimentIntensityAnalyzer()
    sentiment_score = sid.polarity_scores(row)
    positive_meter = sentiment_score['pos']
    negative_meter = sentiment_score['neg']
    neutral_meter = sentiment_score['neu']
    compound_meter = sentiment_score['compound']
    
    if kwargs['k'] == 'positive':
        return positive_meter
    elif kwargs['k'] == 'negative':
        return negative_meter
    elif kwargs['k'] == 'neutral':
        return neutral_meter
    else:
        return compound_meter

#replace null values with empty space
noNull = df['Text'].fillna("")

#tokenize tweets
tokenized_tweet = noNull.apply(lambda x: x.split())

#put list back together
for i in range(len(tokenized_tweet)):
    tokenized_tweet[i] = ' '.join(tokenized_tweet[i])

df['Positive'] = tokenized_tweet.apply(get_sentiment, k= 'positive')
df['Negative'] = tokenized_tweet.apply(get_sentiment, k= 'negative')
df['Neutral'] = tokenized_tweet.apply(get_sentiment, k = 'neutral')
df['Compound'] = tokenized_tweet.apply(get_sentiment, k = 'compound')

df

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


Unnamed: 0  number keyword  \
0      0.943430   65789      TT   
1      0.970177   49400      NK   
2      0.143541   60959     TOM   
3      0.360187   77607      VA   
4      0.779308   58487     TOM   
5      0.359184   77943      VA   
6      0.153355   86771      WN   
7      0.788929   46885      LS   
8      0.909354   22436      BE   
9      0.094547   72338      UA   
10     0.160353   16399      B6   
11     0.227760   52091      QF   
12     0.629340   65344      TT   
13     0.189803   60377     TOM   
14     0.918695    1581      AA   
15     0.502972   54854      TO   
16     0.216359   22399      BE   
17     0.409520   15645      AS   
18     0.910300   45944      LS   
19     0.096877    5540      AA   
20     0.536603   45306      LS   
21     0.131978   62805     TOM   
22     0.171452   12373      AF   
23     0.951226   52094      QF   
24     0.668162     811      AA   
25     0.806601   11809      AF   
26     0.661338   83304      W6   
27     0.967721   68383      U2   
28     0.667780    7503      AC   
29     0.169100   55744      TO   
..          ...     ...     ...   
293    0.713540   14489      AS   
294    0.771143   48281      LS   
295    0.367883   60048     TOM   
296    0.181775   77281      VA   
297    0.991126   65130      TT   
298    0.243927   84326      W6   
299    0.280581   33984      FR   
300    0.332174    7005      AC   
301    0.648780   84521      W6   
302    0.626496   84160      W6   
303    0.662308   87809      WN   
304    0.570786   88396      WN   
305    0.088233   45519      LS   
306    0.412121    5212      AA   
307    0.932134   16202      B6   
308    0.363049   61827     TOM   
309    0.272725    7605      AC   
310    0.587596   18822      B6   
311    0.520768   50257      NK   
312    0.826819   11803      AF   
313    0.971511   15251      AS   
314    0.079147   63374     TOM   
315    0.117393    5936      AA   
316    0.769756   50964      NK   
317    0.519524   80292      VY   
318    0.510298   15909      AS   
319    0.703480   63020     TOM   
320    0.085105   58046     TOM   
321    0.260572   42866      LH   
322    0.299976   76133      UX   

                                                  Text  \
0     Hi there  the best team to assist you is our ...   
1     We re awfully sorry to hear about that  Pleas...   
2    RT   In #Namibia  Melissa and Anna Marie found...   
3     We re sorry to hear this Peter  We would reco...   
4    RT   The Q  #TUIResults are out and show signi...   
5     Hi Olan  we are so pleased to hear this feedb...   
6     Hi there  On May          we will open our sc...   
7     Sorry to hear that  We do hope to see you aga...   
8     Hi Charlotte  thanks for getting in touch  I ...   
9     We re sorry for the disruption  Shea  Can you...   
10    That s disappointing  We can issue a     cred...   
11    Perfection on a plate  We enjoyed having you ...   
12    Our thoughts are with you Walter  keep fighti...   
13   We ve launched our brand new Investor Relation...   
14    We love having you fly with us and will gladl...   
15    Hello  I am sorry for the inconveniences  Can...   
16    Thanks for confirming this with me Emma  I ve...   
17    We re sorry to hear about any frustration  If...   
18    Thanks for getting back to us  we would recom...   
19    We want all of our customers to feel welcome ...   
20    Hi Laura  If you don t cancel the individual ...   
21   Family Holiday Association launches     for   ...   
22        If your query is regarding your trip  ple...   
23    This isn t what we like to hear Jimmy  Can yo...   
24    We re so sorry for the extra travel time toda...   
25    Hello   not a problem  Send us a DM confirmin...   
26    Hey Jose  since those services are different ...   
27    Hi Justin  thanks for getting in touch  I m n...   
28    Please DM us your booking details so we may a...   
29    Hi April  it should be possible to check in  ...   
..                                  

In [4]:
##Cross Validation

from sklearn.model_selection import KFold # import KFold

X=np.array(df['Text'])
y=np.array(df['Rating'])

kf = KFold(n_splits=10) # Define the split - into 2 folds 
kf.get_n_splits(X) # returns the number of splitting iterations in the cross-validator

print(kf) 



KFold(n_splits=10, random_state=None, shuffle=False)


In [5]:
#Function to Train & Run the model
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import metrics
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(stop_words='english', ngram_range = (1,1), max_df = .80, min_df = 1)
vectorizer = TfidfVectorizer(min_df=15)
def run_model(model,modelType):
    scores=list()
    scores_std=list()
    C_s = np.logspace(-10, 0, 10)
    for train_index, test_index in kf.split(X):

        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        if modelType == "KNN":
            #vectorizer = TfidfVectorizer(min_df=15)
            X_train_dtm = vectorizer.fit_transform(X_train)
            X_test_dtm = vectorizer.transform(X_test)
            
        else:
            #vect = CountVectorizer(stop_words='english', ngram_range = (1,1), max_df = .80, min_df = 1)
            #Using training data to transform text into counts of features for each message
            vect.fit(X_train)
            X_train_dtm = vect.transform(X_train) 
            X_test_dtm = vect.transform(X_test)

        #Fit Model
        model.fit(X_train_dtm, y_train)
        y_pred = model.predict(X_test_dtm)

        this_scores=metrics.accuracy_score(y_test,y_pred)*100
        scores.append(np.mean(this_scores))
        scores_std.append(np.std(this_scores))
        
        print('Accuracy Score: ',this_scores,'%',sep='')
        print('Confusion Matrix: ',metrics.confusion_matrix(y_test,y_pred), sep = '\n')
    return scores
 

In [6]:
'''KNN model'''
from sklearn.neighbors import KNeighborsClassifier

#KNN Classifiers
KNN = KNeighborsClassifier(n_neighbors = 1)
scores=run_model(KNN,"KNN")

print('\nK Nearest Neighbors (NN = 1)')
print('Accuracy Score: ',np.mean(scores),'%',sep='')
#print('Confusion Matrix: ',metrics.confusion_matrix(y_test,y_pred), sep = '\n')

Accuracy Score: 78.78787878787878%
Confusion Matrix: 
[[10  0  2]
 [ 1  6  1]
 [ 1  2 10]]
Accuracy Score: 51.515151515151516%
Confusion Matrix: 
[[7 4 1]
 [4 2 2]
 [3 2 8]]
Accuracy Score: 66.66666666666666%
Confusion Matrix: 
[[10  2  0]
 [ 2  3  3]
 [ 4  0  9]]
Accuracy Score: 65.625%
Confusion Matrix: 
[[10  4  2]
 [ 1  3  0]
 [ 3  1  8]]
Accuracy Score: 56.25%
Confusion Matrix: 
[[7 3 3]
 [2 3 1]
 [3 2 8]]
Accuracy Score: 78.125%
Confusion Matrix: 
[[14  2  3]
 [ 1  6  0]
 [ 1  0  5]]
Accuracy Score: 65.625%
Confusion Matrix: 
[[5 4 2]
 [1 7 0]
 [3 1 9]]
Accuracy Score: 65.625%
Confusion Matrix: 
[[8 1 5]
 [3 4 0]
 [1 1 9]]
Accuracy Score: 62.5%
Confusion Matrix: 
[[10  1  5]
 [ 3  4  0]
 [ 1  2  6]]
Accuracy Score: 71.875%
Confusion Matrix: 
[[ 9  2  3]
 [ 1  4  1]
 [ 2  0 10]]

K Nearest Neighbors (NN = 1)
Accuracy Score: 66.2594696969697%


In [7]:
'''Logistic Regression'''

from sklearn.linear_model import LogisticRegression

#logistic regression
LR = LogisticRegression()
scores=run_model(LR,"LR")

print('\nLogistic Regression')
print('Accuracy Score: ',np.mean(scores),'%',sep='')


Accuracy Score: 

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


87.87878787878788%
Confusion Matrix: 
[[11  0  1]
 [ 2  6  0]
 [ 1  0 12]]
Accuracy Score: 78.78787878787878%
Confusion Matrix: 
[[11  1  0]
 [ 3  5  0]
 [ 2  1 10]]
Accuracy Score: 75.75757575757575%
Confusion Matrix: 
[[10  2  0]
 [ 3  4  1]
 [ 2  0 11]]
Accuracy Score: 90.625%
Confusion Matrix: 
[[14  1  1]
 [ 1  3  0]
 [ 0  0 12]]
Accuracy Score: 84.375%
Confusion Matrix: 
[[11  2  0]
 [ 2  4  0]
 [ 1  0 12]]
Accuracy Score: 90.625%
Confusion Matrix: 
[[17  1  1]
 [ 1  6  0]
 [ 0  0  6]]
Accuracy Score: 87.5%
Confusion Matrix: 
[[10  1  0]
 [ 2  6  0]
 [ 1  0 12]]
Accuracy Score: 90.625%
Confusion Matrix: 
[[14  0  0]
 [ 0  7  0]
 [ 1  2  8]]
Accuracy Score: 78.125%
Confusion Matrix: 
[[12  3  1]
 [ 2  5  0]
 [ 1  0  8]]
Accuracy Score: 96.875%
Confusion Matrix: 
[[13  1  0]
 [ 0  6  0]
 [ 0  0 12]]

Logistic Regression
Accuracy Score: 86.11742424242424%


In [8]:
'''Support Vector Machine'''
from sklearn.svm import LinearSVC

#SVM
SVM = LinearSVC(penalty='l2', loss='squared_hinge')
#kernel = 'linear', random_state = 0

scores=run_model(SVM,"SVM")
print('\nSupport Vector Machine')
print('Accuracy Score: ',np.mean(scores),'%',sep='')


Accuracy Score: 75.75757575757575%
Confusion Matrix: 
[[ 9  1  2]
 [ 2  6  0]
 [ 3  0 10]]
Accuracy Score: 75.75757575757575%
Confusion Matrix: 
[[10  2  0]
 [ 3  5  0]
 [ 2  1 10]]
Accuracy Score: 81.81818181818183%
Confusion Matrix: 
[[10  2  0]
 [ 1  6  1]
 [ 2  0 11]]
Accuracy Score: 87.5%
Confusion Matrix: 
[[13  2  1]
 [ 1  3  0]
 [ 0  0 12]]
Accuracy Score: 81.25%
Confusion Matrix: 
[[ 9  4  0]
 [ 1  5  0]
 [ 1  0 12]]
Accuracy Score: 81.25%
Confusion Matrix: 
[[15  3  1]
 [ 1  6  0]
 [ 1  0  5]]
Accuracy Score: 84.375%
Confusion Matrix: 
[[ 9  1  1]
 [ 2  6  0]
 [ 1  0 12]]
Accuracy Score: 90.625%
Confusion Matrix: 
[[14  0  0]
 [ 0  7  0]
 [ 1  2  8]]
Accuracy Score: 81.25%
Confusion Matrix: 
[[12  3  1]
 [ 1  6  0]
 [ 1  0  8]]
Accuracy Score: 93.75%
Confusion Matrix: 
[[12  1  1]
 [ 0  6  0]
 [ 0  0 12]]

Support Vector Machine
Accuracy Score: 83.33333333333333%


In [9]:
'''Random Forest Classifier'''
from sklearn.ensemble import RandomForestClassifier

RFC = RandomForestClassifier(n_estimators = 3,random_state=0)
scores=run_model(RFC,"RFC")

print('\n Random Forest Classifier')
print('Accuracy Score: ',np.mean(scores),'%',sep='')


Accuracy Score: 69.6969696969697%
Confusion Matrix: 
[[11  0  1]
 [ 6  2  0]
 [ 3  0 10]]
Accuracy Score: 72.72727272727273%
Confusion Matrix: 
[[10  1  1]
 [ 5  3  0]
 [ 0  2 11]]
Accuracy Score: 60.60606060606061%
Confusion Matrix: 
[[11  0  1]
 [ 7  1  0]
 [ 5  0  8]]
Accuracy Score: 78.125%
Confusion Matrix: 
[[11  3  2]
 [ 1  3  0]
 [ 1  0 11]]
Accuracy Score: 65.625%
Confusion Matrix: 
[[10  0  3]
 [ 4  1  1]
 [ 3  0 10]]
Accuracy Score: 59.375%
Confusion Matrix: 
[[10  4  5]
 [ 1  5  1]
 [ 2  0  4]]
Accuracy Score: 78.125%
Confusion Matrix: 
[[11  0  0]
 [ 7  1  0]
 [ 0  0 13]]
Accuracy Score: 78.125%
Confusion Matrix: 
[[12  2  0]
 [ 0  7  0]
 [ 3  2  6]]
Accuracy Score: 87.5%
Confusion Matrix: 
[[16  0  0]
 [ 4  3  0]
 [ 0  0  9]]
Accuracy Score: 68.75%
Confusion Matrix: 
[[9 5 0]
 [0 6 0]
 [5 0 7]]

 Random Forest Classifier
Accuracy Score: 71.8655303030303%


In [10]:
'''Naive Bayes Model'''

from sklearn.naive_bayes import MultinomialNB

#Naive Bayes Model
NB = MultinomialNB()
scores=run_model(NB,"NB")

print('\nNaive Bayes')
print('Accuracy Score: ',np.mean(scores),'%',sep='')


Accuracy Score: 87.87878787878788%
Confusion Matrix: 
[[11  0  1]
 [ 2  5  1]
 [ 0  0 13]]
Accuracy Score: 66.66666666666666%
Confusion Matrix: 
[[ 9  0  3]
 [ 4  2  2]
 [ 1  1 11]]
Accuracy Score: 60.60606060606061%
Confusion Matrix: 
[[ 7  1  4]
 [ 3  2  3]
 [ 2  0 11]]
Accuracy Score: 75.0%
Confusion Matrix: 
[[ 9  0  7]
 [ 1  3  0]
 [ 0  0 12]]
Accuracy Score: 81.25%
Confusion Matrix: 
[[11  0  2]
 [ 3  2  1]
 [ 0  0 13]]
Accuracy Score: 65.625%
Confusion Matrix: 
[[13  1  5]
 [ 1  2  4]
 [ 0  0  6]]
Accuracy Score: 78.125%
Confusion Matrix: 
[[10  0  1]
 [ 5  2  1]
 [ 0  0 13]]
Accuracy Score: 87.5%
Confusion Matrix: 
[[12  0  2]
 [ 0  6  1]
 [ 1  0 10]]
Accuracy Score: 62.5%
Confusion Matrix: 
[[10  0  6]
 [ 1  2  4]
 [ 1  0  8]]
Accuracy Score: 90.625%
Confusion Matrix: 
[[14  0  0]
 [ 2  3  1]
 [ 0  0 12]]

Naive Bayes
Accuracy Score: 75.57765151515152%


In [11]:
#Predict the Unlabled datset

X=np.array(df_new_data['Text'].values.astype('U'))
X_train_dtm = vect.transform(X) 

y_pred = SVM.predict(X_train_dtm)

print('\n SVM Regression',y_pred)



 SVM Regression ['N' 'H' 'H' ... 'H' 'N' 'U']


In [12]:
df_new_data["rating"]=y_pred
df_new_data.head()

df_new_data.to_csv(r'D:\Travelytics Project\Data\SA_Tweets_Predicted.csv')